import { ReactNode } from 'react'
import './globals.css'
// eslint-disable-next-line camelcase
import { Poppins, Roboto_Slab } from 'next/font/google'
import Header from '@/components/header/Header'

const rbtSlab = Roboto_Slab({
  weight: ['400'],
  subsets: ['latin'],
  variable: '--font-robotoslab',
})

const poppins = Poppins({
  weight: ['400', '600', '900', '500', '800'],
  subsets: ['latin'],
  variable: '--font-poppins',
})

export const metadata = {
  title: 'Tech Web Solution',
  description: 'Generated by create next app',
}

/**
 * RootLayout component
 *
 * @param children - The child components to render
 * @returns The root layout component
 */
export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    // Render the HTML document with the lang attribute set to "en"
    <html lang="en">
      <body
        // Apply the CSS classes to the body element
        className={`${poppins.className} ${rbtSlab.className} relative font-poppins`}
      >
        {/* Render the Header component */}
        <Header />
        {/* Render the child components */}
        {children}
      </body>
    </html>
  )
}
