import { ReactNode } from 'react'
import './globals.css'
// eslint-disable-next-line camelcase
import { Poppins, Roboto_Slab } from 'next/font/google'
import Header from '@/components/header/Header'

const rbtSlab = Roboto_Slab({
  weight: ['400'],
  subsets: ['latin'],
  variable: '--font-robotoslab',
})

const poppins = Poppins({
  weight: ['400', '900', '500', '800'],
  subsets: ['latin'],
  variable: '--font-poppins',
})

export const metadata = {
  title: 'Tech Web Solution',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} ${rbtSlab.className} relative`}>
        <Header />
        {children}
      </body>
    </html>
  )
}
